language: objective-c
osx_image: mavericks
notifications:
  email: false
# branches:
#   only:
#     - master
env:
  matrix:
    - CI_CONFIG=unit
    - CI_CONFIG=build
before_script:
  - ./ci/before_script.sh
script:  
  - ./ci/script.sh
