language: objective-c
osx_image: mavericks
notifications:
  email: false
branches:
  only:
    - master
before_script:
  # - ./ci/install-node.sh
  - ./ci/install-android.sh
  # - npm install -g jshint grunt-cli
  # - npm install
script:  
  # - npm test
  # - ./reset.sh --hardcore --real-safari --ios
