language: objective-c
osx_image: mavericks
notifications:
  email: false
# branches:
#   only:
#     - master
env:
  matrix:
    - CI_CONFIG=unit
    - CI_CONFIG=build
before_script:
  - ./ci/install-node.sh
  - ./ci/show-env.sh
  - npm install -g jshint grunt-cli
  - ./ci/before_script_extra.sh
script:  
  - ./ci/script.sh
